config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers'  => 'relationships#followers',  as: 'followers'
      get "unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
      patch "withdraw" => "customers#withdraw", as: "withdraw"
      member do
        get 'favorites'
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :food_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'search'
      end
    end
    resources :rooms,    only: [:create, :index, :show]
    resources :messages, only: [:create]
    resources :groups do
      resources :group_comments, only: [:create, :destroy]
      get "join" => "groups#join"
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts,     only: [:index, :show, :destroy] do
      resources :food_comments, only: [:destroy]
      collection do
        get 'search'
      end
    end
    resources :groups do
      resources :group_comments, only: [:destroy]
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  belongs_to :prefecture, optional: true

  has_many :posts,           dependent: :destroy
  has_many :favorites,       dependent: :destroy
  has_many :food_comments,   dependent: :destroy
  has_many :entries,         dependent: :destroy
  has_many :messages,        dependent: :destroy
  has_many :group_customers, dependent: :destroy
  has_many :group_comments,  dependent: :destroy
  has_many :groups, through: :group_customers
  # フォローした、されたの関係
  has_many :relationships,            class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使用
  has_many :followings,    through: :relationships,            source: :followed
  has_many :followers,     through: :reverse_of_relationships, source: :follower

  def get_profile_image
    (profile_image.attached?) ? profile_image: 'no_image.jpg'
  end

  def follow(customer_id)
    customer = Customer.find(customer_id)
    relationships.find_or_create_by(followed_id: customer.id)
  end

  def unfollow(customer_id)
    customer = Customer.find(customer_id)
    relationship = relationships.find_by(followed_id: customer.id)
    relationship.destroy if relationship
  end

  def following?(customer)
    followings.include?(customer)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.order("created_at DESC")

    @fdivs = []
    @posts.each do |post|
      stars = []
      post.food_comments.each do |food_comment|
        stars.push(food_comment.star.to_i)
      end
      fdiv = stars.sum.fdiv(stars.length)

      if fdiv.nan?
        fdiv = ""
      end
      @fdivs.push(fdiv)
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:profile_image, :name, :prefecture_id, :food, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>会員編集</h4>
  </div>

  <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <div class="row mt-3">
      <div class="col-2">会員ID</div>
      <div class="col-3"><%= @customer.id %></div>
    </div>
    <div class="row mt-2">
      <div class="col-2"><%= f.label "プロフィール画像" %></div>
      <div class0"col-3"><%= f.file_field :profile_image, accept: "image/*" %></div>
    </div>
    <div class="row mt-2">
      <div class="col-2"><%= f.label "名前" %></div>
      <div class="col-3"><%= f.text_field :name %></div>
    </div>
    <div class="row mt-2">
      <div class="col-2"><%= f.label "好きな場所" %></div>
      <div class="col-3"><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %></div>
    </div>
    <div class="row mt-2">
      <div class="col-2"><%= f.label "好きな食べ物" %></div>
      <div class="col-3"><%= f.text_field :food %></div>
    </div>
    <div class="row mt-2">
      <div class="col-2">メールアドレス</div>
      <div class="col-3"><%= @customer.email %></div>
    </div>
    <div class="row mt-2">
      <div class="col-2"><%= f.label "ステータス" %></div>
      <div class="col-3"><%= f.radio_button :is_deleted, false %>有効　<%= f.radio_button :is_deleted, true %>退会</div>
    </div>

    <div class="row d-flex justify-content-center mt-3">
      <div class="col-3"><%= f.submit "編集内容を保存", class: "btn btn-success" %></div>
    </div>
  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>会員一覧</h4>
  </div>

  <table class="table">
    <thead style="background-color:#FFCC66;">
      <tr>
        <th>会員ID</th>
        <th>プロフィール画像</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= image_tag customer.get_profile_image, size: '80x80' %></td>
          <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="text-secondary">退会</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row justify-content-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>会員詳細</h4>
  </div>

  <div class="row mt-3">
    <table class="table col-3">
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>プロフィール画像</td>
        <td><%= image_tag @customer.get_profile_image, size:'80x80' %></td>
      </tr>
      <tr>
        <td>名前</td>
        <td><%= @customer.name %></td>
      </tr>
      <tr>
        <td>好きな場所</td>
        <td><%= @customer.prefecture&.name %></td>
      </tr>
      <tr>
        <td>好きな食べ物</td>
        <td><%= @customer.food %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>ステータス</td>
        <td>
          <% if @customer.is_deleted == false %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="text-secondary">退会</p>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="col-9">
      <div class="container">
        <div class="row">
          <%= render 'admin/posts/index', posts: @posts, fdivs: @fdivs %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-3">
      <%= link_to "編集", edit_admin_customer_path, class: "btn btn-success btn-block" %>
    </div>
  </div>

</div>