config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers'  => 'relationships#followers',  as: 'followers'
      get "unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
      patch "withdraw" => "customers#withdraw", as: "withdraw"
      member do
        get 'favorites'
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :food_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'search'
      end
    end
    resources :rooms,    only: [:create, :index, :show]
    resources :messages, only: [:create]
    resources :groups do
      resources :group_comments, only: [:create, :destroy]
      get "join" => "groups#join"
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts,     only: [:index, :show, :destroy] do
      resources :food_comments, only: [:destroy]
      collection do
        get 'search'
      end
    end
    resources :groups do
      resources :group_comments, only: [:destroy]
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :favorites,     dependent: :destroy
  has_many :food_comments, dependent: :destroy
  has_many :post_tags,     dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  has_one_attached :image

  belongs_to :customer
  belongs_to :prefecture

  validates :image,         presence: true
  validates :prefecture_id, presence: true
  validates :food_name,     presence: true
  validates :introduction,  presence: true, length:{maximum: 50}

  scope :latest,     -> {order(created_at: :desc)}
  scope :old,        -> {order(created_at: :asc)}
  scope :star_count, -> {find(FoodComment.group(:post_id).order('avg(star) desc').pluck(:post_id))}

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags
    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    if params[:latest]
      @posts = Post.latest
    elsif params[:old]
      @posts = Post.old
    elsif params[:star_count]
      @posts = Post.star_count
    else
      @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all.order("created_at DESC")
    end

    @fdivs = []
    @posts.each do |post|
      stars = []
      post.food_comments.each do |food_comment|
        stars.push(food_comment.star.to_i)
      end
      fdiv = stars.sum.fdiv(stars.length)

      if fdiv.nan?
        fdiv = ""
      end
      @fdivs.push(fdiv)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_tags = @post.tags
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def search
    @results = @q.result(distinct: true).order("created_at DESC")

    @fdivs = []
    @results.each do |post|
      stars = []
      post.food_comments.each do |food_comment|
        stars.push(food_comment.star.to_i)
      end
      fdiv = stars.sum.fdiv(stars.length)

      if fdiv.nan?
        fdiv = ""
      end
      @fdivs.push(fdiv)
    end
  end

  private

  def post_params
    params.require(:post).permit(:food_name, :introduction, :prefecture_id, :comment, :image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<table class="table">
  <thead style="background-color:#FFCC66;">
    <tr>
      <th>投稿日時</th>
      <th>食べ物画像</th>
      <th>都道府県名</th>
      <th>食べ物名</th>
      <th>評価</th>
      <th>説明</th>
      <th>タグ</th>
      <th>コメント数</th>
    </tr>
  </thead>
  <tbody>
    <% posts.each_with_index do |post, i| %>
      <tr>
        <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
        <td><%= image_tag post.image, size: "80x80" %></td>
        <td><%= post.prefecture.name %></td>
        <td>
          <%= link_to admin_post_path(post.id) do %>
            <% post.food_name %>
          <% end %>
        </td>
        <td><%= @fdivs[i].to_f.round(1) %></td>
        <td><%= post.introduction.truncate(10) %></td>
        <td><%= post.tags.map(&:name).join(', ') %></td>
        <td><%= post.food_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>投稿一覧</h4>
  </div>

  <div class="row">
    <%= link_to "新しい順", admin_posts_path(latest: "true") %>
    |<%= link_to "古い順", admin_posts_path(old: "true") %>
    |<%= link_to "評価の高い順", admin_posts_path(star_count: "true") %>
  </div>

  <div class="row">
    <%= form_tag admin_posts_path, method: :get, class: "boards__searchForm" do %>
      <%= select_tag :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
      {prompt: "タグで絞り込み検索", onchange: "submit(this.form);"} %>
    <% end %>
  </div>

  <div class="row mt-3">
    <%= render 'admin/posts/index', posts: @posts %>
  </div>
</div>

app/views/admin/posts/search.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>検索一覧</h4>
  </div>

  <div class="row mt-3">
    <table class="table">
      <thead style="background-color:#FFCC66;">
        <tr>
          <th><%= sort_link(@q, :created_at, "投稿日時") %></th>
          <th>食べ物画像</th>
          <th>都道府県名</th>
          <th><%= sort_link(@q, :food_name, "食べ物名") %></th>
          <th>評価</th>
          <th>説明</th>
          <th>タグ</th>
          <th>コメント数</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each_with_index do |post, i| %>
          <tr>
            <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= image_tag post.image, size: "80x80" %></td>
            <td><%= post.prefecture.name %></td>
            <td>
              <%= link_to admin_post_path(post.id) do %>
                <% post.food_name %>
              <% end %>
            </td>
            <td><%= @fdivs[i].to_f.round(1) %></td>
            <td><%= post.introduction.truncate(10) %></td>
            <td><%= post.tags.map(&:name).join(', ') %></td>
            <td><%= post.food_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>投稿詳細</h4>
  </div>

  <div class="row">
    <%= @post.created_at.strftime('%Y/%m/%d') %>
    <%= @post.customer.name %>
  </div>

  <div class="row mt-3">
    <div class="col-5">
      <%= image_tag @post.image, size: "300x300" %>
    </div>

    <div class="col-7">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>都道府県</th>
            <td><%= @post.prefecture&.name %></td>
          </tr>
          <tr>
            <th>食べ物名</th>
            <td><%= @post.food_name %></td>
          </tr>
          <tr>
            <th>食べ物説明</th>
            <td><%= @post.introduction %></td>
          </tr>
          <tr>
            <th>タグ</th>
            <td>
              <% @post_tags.each do |tag| %>
                <%= tag.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>コメント数</th>
            <td><%= @post.food_comments.count %></td>
          </tr>
          <tr>
            <td><%= link_to "削除", admin_post_path(@post), method: :delete, class: "btn btn-danger" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div id="comment_area">
    <%= render 'admin/food_comments/index', post: @post %>
  </div>

</div>