config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers'  => 'relationships#followers',  as: 'followers'
      get "unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
      patch "withdraw" => "customers#withdraw", as: "withdraw"
      member do
        get 'favorites'
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :food_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'search'
      end
    end
    resources :rooms,    only: [:create, :index, :show]
    resources :messages, only: [:create]
    resources :groups do
      resources :group_comments, only: [:create, :destroy]
      get "join" => "groups#join"
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts,     only: [:index, :show, :destroy] do
      resources :food_comments, only: [:destroy]
      collection do
        get 'search'
      end
    end
    resources :groups do
      resources :group_comments, only: [:destroy]
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_customers, dependent: :destroy
  has_many :group_comments,  dependent: :destroy
  has_many :customers, through: :group_customers

  has_one_attached :group_image

  validates :name,         presence: true, length:{maximum: 20}
  validates :introduction, presence: true, length:{maximum: 50}

  def get_group_image
    (group_image.attached?) ? group_image: 'no_image.jpg'
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController

  def index
    @groups = Group.all.order("created_at DESC")
  end

  def show
    @group = Group.find(params[:id])
  end

  def all_destroy
    @group = Group.find(params[:group_id])
    if @group.destroy
      redirect_to admin_groups_path
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image, :comment)
  end

end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/index.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>グループ一覧</h4>
  </div>

  <div class="row mt-3">
    <table class="table">
      <thead style="background-color:#FFCC66;">
        <tr>
          <th class="col-2">グループ画像</th>
          <th class="col-2">グループ名</th>
          <th class="col-5">紹介文</th>
          <th class="col-2">メンバー数</th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= image_tag group.get_group_image, size: "80x80" %></td>
            <td><%= link_to group.name, admin_group_path(group) %></td>
            <td><%= group.introduction.truncate(25) %></td>
            <td><%= group.customers.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/groups/show.html.erb
<div class="container">
  <div class="row mt-5">
    <h4>グループ詳細</h4>
  </div>

  <div class="row mt-3">
    <table class="table col-3">
      <tr>
        <td>グループ画像</td>
        <td><%= image_tag @group.get_group_image, size: "80x80" %></td>
      </tr>
      <tr>
        <td>グループ名</td>
        <td><%= @group.name %></td>
      </tr>
      <tr>
        <td>紹介文</td>
        <td><%= @group.introduction %></td>
      </tr>
      <tr>
        <td>メンバー</td>
        <td>
          <% @group.customers.each do |member| %>
            <li><%= member.name %></li>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="col-9">
      <div id="comment_area">
        <%= render 'admin/group_comments/index', group: @group %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-3">
      <%= link_to "グループ解散", admin_group_all_destroy_path(@group), method: :delete, class: "btn btn-danger btn-block" %>
    </div>
  </div>
</div>