config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers'  => 'relationships#followers',  as: 'followers'
      get "unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
      patch "withdraw" => "customers#withdraw", as: "withdraw"
      member do
        get 'favorites'
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :food_comments, only: [:create, :destroy]
      resource  :favorites,     only: [:create, :destroy]
      collection do
        get 'search'
      end
    end
    resources :rooms,    only: [:create, :index, :show]
    resources :messages, only: [:create]
    resources :groups do
      resources :group_comments, only: [:create, :destroy]
      get "join" => "groups#join"
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts,     only: [:index, :show, :destroy] do
      resources :food_comments, only: [:destroy]
      collection do
        get 'search'
      end
    end
    resources :groups do
      resources :group_comments, only: [:destroy]
      delete "all_destroy" => "groups#all_destroy"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  belongs_to :prefecture, optional: true

  has_many :posts,           dependent: :destroy
  has_many :favorites,       dependent: :destroy
  has_many :food_comments,   dependent: :destroy
  has_many :entries,         dependent: :destroy
  has_many :messages,        dependent: :destroy
  has_many :group_customers, dependent: :destroy
  has_many :group_comments,  dependent: :destroy
  has_many :groups, through: :group_customers
  # フォローした、されたの関係
  has_many :relationships,            class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使用
  has_many :followings,    through: :relationships,            source: :followed
  has_many :followers,     through: :reverse_of_relationships, source: :follower

  def get_profile_image
    (profile_image.attached?) ? profile_image: 'no_image.jpg'
  end

  def follow(customer_id)
    customer = Customer.find(customer_id)
    relationships.find_or_create_by(followed_id: customer.id)
  end

  def unfollow(customer_id)
    customer = Customer.find(customer_id)
    relationship = relationships.find_by(followed_id: customer.id)
    relationship.destroy if relationship
  end

  def following?(customer)
    followings.include?(customer)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :customer
  belongs_to :room

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :post

end

app/models/food_comment.rb
class FoodComment < ApplicationRecord

  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true, length:{maximum:200}

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_customers, dependent: :destroy
  has_many :group_comments,  dependent: :destroy
  has_many :customers, through: :group_customers

  has_one_attached :group_image

  validates :name,         presence: true, length:{maximum: 20}
  validates :introduction, presence: true, length:{maximum: 50}

  def get_group_image
    (group_image.attached?) ? group_image: 'no_image.jpg'
  end

end

app/models/group_comment.rb
class GroupComment < ApplicationRecord

  belongs_to :customer
  belongs_to :group

  validates :comment, presence: true, length:{maximum: 200}

end

app/models/group_customer.rb
class GroupCustomer < ApplicationRecord

  belongs_to :customer
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :customer
  belongs_to :room

  validates :content, presence: true, length:{maximum: 200}

end

app/models/post.rb
class Post < ApplicationRecord

  has_many :favorites,     dependent: :destroy
  has_many :food_comments, dependent: :destroy
  has_many :post_tags,     dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  has_one_attached :image

  belongs_to :customer
  belongs_to :prefecture

  validates :image,         presence: true
  validates :prefecture_id, presence: true
  validates :food_name,     presence: true
  validates :introduction,  presence: true, length:{maximum: 50}

  scope :latest,     -> {order(created_at: :desc)}
  scope :old,        -> {order(created_at: :asc)}
  scope :star_count, -> {find(FoodComment.group(:post_id).order('avg(star) desc').pluck(:post_id))}

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags
    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

end

app/models/post_tag.rb
class PostTag < ApplicationRecord

  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id,  presence: true

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  has_many :customers
  has_many :posts,    dependent: :destroy

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries,  dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿をもつ それは、post_tagsを通じて参照できる
  has_many :posts, through: :post_tags

  validates :name, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_q

  private

  def set_q
    # params[:q]のqには検索ファームに入力した値が入る
    @q = Post.ransack(params[:q])
  end

end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer style="background-color:#0099FF;">
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>travel food</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#0099FF;">
    <div class="container">
      <nav class="navbar-brand navbar-left header-logo">
        <%= link_to image_tag("food.png", size: "70x50"), root_path, class: "header-button btn text-light" %>
      </nav>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav ml-auto">
          <!-- 顧客がログインしている時 -->
          <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.name %>さん！</p>
            <li><%= link_to "会員詳細", customer_path(current_customer), class: "btn header-button text-light" %></li>
            <li><%= link_to "会員一覧", customers_path, class: "btn header-button text-light" %> </li>
            <li><%= link_to "グループ一覧", groups_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "投稿一覧", posts_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn header-button text-light" %></li>
            <li><%= search_form_for @q, url: search_posts_path do |f| %>
                  <%= f.text_field :food_name_or_prefecture_name_cont, placeholder:"食べ物名or都道府県名" %>
                  <%= f.submit "検索" %>
                <% end %>
            </li>

          <!-- 管理者がログインしている時 -->
          <% elsif admin_signed_in? %>
            <li><%= link_to "会員一覧", admin_customers_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "グループ一覧", admin_groups_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "投稿一覧", admin_posts_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn header-button text-light" %></li>
            <li><%= search_form_for @q, url: search_admin_posts_path do |f| %>
                  <%= f.text_field :food_name_or_prefecture_name_cont, placeholder:"食べ物名or都道府県名" %>
                  <%= f.submit "検索" %>
                <% end %>
            </li>

          <!-- 顧客がログインしていない時 -->
          <% else %>
            <li><%= link_to "Home", root_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "About", about_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "新規登録", new_customer_registration_path, class: "btn header-button text-light" %></li>
            <li><%= link_to "ログイン", new_customer_session_path, class: "btn header-button text-light" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelfood</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main class="mb-5">
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>